version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: prisma-teste
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "6000:5432"
